### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by forwardwin** [Fuzion24/JustTrustMe#19]
have you hook any version of instagram?

**Comment by forwardwin** [comment]
I found out that instagram use ch.boye.httpclientandroidlib instead.

**Comment by Manouchehri** [comment]
What did you end up using to sniff/bypass SSL?

**Comment by ranjbarhadi** [comment]
@forwardwin @Manouchehri any luck with new Instagram client(ver 10.18)?

**Comment by Code8525** [comment]
10.33?

**Comment by ranjbarhadi** [comment]
Still not working

**Comment by Code8525** [comment]
If other methods like disable ssl pinning

**Comment by xgemboy** [comment]
@ranjbarhadi @Code8525 I have bypassed SSL pinning of latest version of Instagram APK. contact me on xgemboy@gmail.com for more details.

**Comment by Manouchehri** [comment]
To save everyone time, he wants $500 for it... 🙄

**Comment by kolsab** [comment]
You can take from me 5 times cheaper APK + sigkey in the kit. All new versions will be free on request.
Proof video http://rgho.st/85K7SlBS8

Interesing? contact me to telegram https://t.me/kolsab

**Comment by kilua626** [comment]
@Manouchehri I can mitm Instagram(12 or 65) for android
