### ISSUE TITLE
not work on genymotion 2.6 

### ISSUE THREAD

**Issue by stayliv3** [Fuzion24/JustTrustMe#20]
* Genymotion - 2.6.0
- Custom Phone - 5.1.0 - API 22 - 768x1280
* Xposed-v80-sdk22-x86
* XposedInstaller_3.0_alpha4
justtrustme binary 2.0

xposed log:

05-13 05:32:40.211 I/Xposed  (  472): -----------------
05-13 05:32:40.211 I/Xposed  (  472): Starting Xposed version 80, compiled for SDK 22
05-13 05:32:40.211 I/Xposed  (  472): Device: Custom Phone - 5.1.0 - API 22 - 768x1280 (unknown), Android version 5.1 (SDK 22)
05-13 05:32:40.211 I/Xposed  (  472): ROM: vbox86p-userdebug 5.1 LMY47D eng.buildbot.20151117.200402 test-keys
05-13 05:32:40.211 I/Xposed  (  472): Build fingerprint: generic/vbox86p/vbox86p:5.1/LMY47D/buildbot11172007:userdebug/test-keys
05-13 05:32:40.211 I/Xposed  (  472): Platform: x86, 32-bit binary, system server: yes
05-13 05:32:40.211 I/Xposed  (  472): SELinux enabled: no, enforcing: no
05-13 05:32:42.547 I/Xposed  (  472): -----------------
05-13 05:32:42.548 I/Xposed  (  472): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-13 05:32:42.673 I/Xposed  (  472): Detected ART runtime
05-13 05:32:42.684 I/Xposed  (  472): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-13 05:32:42.764 I/Xposed  (  472): Loading modules from /data/app/just.trust.me-1/base.apk
05-13 05:32:42.823 I/Xposed  (  472):   Loading class just.trust.me.Main

after loading class just.trust.me.Main  it has nothing.when i run the app.the burp could proxy the https traffic.

**Comment by Fuzion24** [comment]
supporting genymotion is out of scope for this project, sorry.  but maybe try an app that doesn't use https just to see that you can proxy the traffic at all.

**Comment by stayliv3** [comment]
thanks for your reply。It works on the genymotion。it is the proxy has some problem ,i reboot it and it works fine now.
