### ISSUE TITLE
Does not work with Handelsbanken 7.2.0.

### ISSUE THREAD

**Issue by Ogglas** [Fuzion24/JustTrustMe#24]
It has worked flawlessly before but with the new Handelsbanken version it does not work anymore. Tried updated versions of Facebook and Facebook Messenger and they are also not intercepted anymore.

**Comment by OskarGroth** [comment]
@Ogglas Did you end up finding an alternative to JustTrustMe?

**Comment by Fuzion24** [comment]
They likely updated the HTTP library they were using.  Feel free to decompile it and send a patch
