### ISSUE TITLE
Not able to bypass pinning in Twitter app 5.47.0

### ISSUE THREAD

**Issue by clviper** [Fuzion24/JustTrustMe#3]
Im using Genymotion with an Android 4.3 + Xposed 2.6.1 and the bypass is not working. No errors exist in the logs. Could you double check if in your setup you are able to bypass it?
Thank you.

**Comment by jakev** [comment]
@clviper have you tried using my fork: https://github.com/jakev/JustTrustMe?

**Comment by clviper** [comment]
Hi. Just compiled your fork but the behavior is the same.

**Comment by jakev** [comment]
It does not appear to work for me either. I just pushed a commit that I thought would address it (https://github.com/jakev/JustTrustMe/commit/7fb02781f8da90c8dd3ad92c5310ba5c48402cd9), but I guess no dice.  I will try to look into this tonight if I get some free time.

**Comment by clviper** [comment]
Thank you. I will try to help you out also, probably they implemented a custom pinning functionality, I´m going to look at the app.

**Comment by clviper** [comment]
Hi there. Any news on this issue? Thank you.

**Comment by Fuzion24** [comment]
How are you mitm'ing the app?  I'm suspect parts of this app might not be using HTTP.  I didn't dig too deeply, but I was able to using mitmproxy to snag registration, but not not stuff from the timeline (even though it was loading properly)

**Comment by testmanager92** [comment]
Any updates on this guys?

I've came across an app which uses amqp protocol. Is this applicable to twitter as well?

**Comment by clviper** [comment]
On the case of twitter, with an up to date version of the app the bypass worked.

**Comment by testmanager92** [comment]
Is it working for all the internal pages or just the login form?

**Comment by clviper** [comment]
It looks like twitter is not respecting proxy anymore. I have tried with JustTrustMe and with Cydia Substrate+SSLTrustKiller and the behaviour is the same.

**Comment by Alexzha** [comment]
Did anyone get this working? Doesn't work for me either...

**Comment by Fuzion24** [comment]
What specifically doesn't work for you?

**Comment by Alexzha** [comment]
I've downloaded the latest twitter apk and attempted to MiTM it using this module...There simply isn't any traffic to be seen; i figured maybe the app ignores wifi proxy settings so i used proxydroid (which uses iptables i believe) and afterwards it says "No request was made. Possibly the SSL certificate was rejected.".

Have you had sucess intercepting the latest twitter app traffic?

The last one that works is version ~5.20 or so

**Comment by Fuzion24** [comment]
I think this should fix it: https://github.com/Fuzion24/JustTrustMe/commit/482d1166d1ebb8ffce2ab6e771469b6ed6ce61ea
