### ISSUE TITLE
error with some apps though there is no decrypting enabled

### ISSUE THREAD

**Issue by HamidZaeri** [Fuzion24/JustTrustMe#39]
After I Installed JTM, one of my installed app (in Fiddler decrypt HTTPS is unchecked), My app says there is no connection to internet (The same error when decrypt https is enabled and jtm not installed).
I hope you got me!

**Comment by Fuzion24** [comment]
Not enough information.

**Comment by HamidZaeri** [comment]
Updated first post.
Does jtm support native layer ssl pinned app?

**Comment by Fuzion24** [comment]
no, it does not -> Does jtm support native layer ssl pinned app?
Consider using something like Frida for that.
