### ISSUE TITLE
The inner webview or Chrome get SSL Error With HTTPS

### ISSUE THREAD

**Issue by yaochao** [Fuzion24/JustTrustMe#41]
When I visit a https url, I can't get it. But a http url.
So I guess the webview hook are lose efficacy.

**Comment by vicliu1990** [comment]
me too

**Comment by foundkey** [comment]
Me to, if enable JustTrustMe Module, can't use inner webview access URL.
Use Logcat can capture exception:
`Error creating trust manager (just.trust.me.Main$ImSureItsLegitTrustManager): java.lang.IllegalArgumentException`

**Comment by foundkey** [comment]
Find "ImSureItsLegitTrustManager" class in Main.java, and add method:

`
public List<X509Certificate> checkServerTrusted(X509Certificate[] chain, String authType, String host) throws CertificateException {
    List<X509Certificate> list = new ArrayList<>();
    return list;
}
`
rebuild and install, done.

**Comment by yaochao** [comment]
Good job.

**Comment by yaochao** [comment]
> Find "ImSureItsLegitTrustManager" class in Main.java, and add method:
> 
> `public List<X509Certificate> checkServerTrusted(X509Certificate[] chain, String authType, String host) throws CertificateException { List<X509Certificate> list = new ArrayList<>(); return list; }`
> rebuild and install, done.

you can contribute this code, and pull requests it.

**Comment by Fuzion24** [comment]
Fixed by #43
