### ISSUE TITLE
Chrome HTTPS requests arn't going through

### ISSUE THREAD

**Issue by theSmallNothing** [Fuzion24/JustTrustMe#6]
After activating the module on Android 4.4.4, Xposed 2.6.1, Chrome 42.0.2311.111, all Chrome HTTPS requests fail with a "Webpage Unavailable" error message. First I thought it was a connection problem but after a bit of messing about I found I could reliably create the error just by activating and deactivating this module.

Further messing about put the problem at the `javax.net.ssl.TrustManagerFactory` `getTrustManagers` hook. I think Chrome is expecting a `X509ExtendedTrustManager` instance in the returned list and when it can't find one hangs resulting finally with a "Webpage Unavailable" error, but that's just conjecture.

The weird thing is if you hook all the `checkServerTrusted` of the `com.android.org.conscrypt.TrustManagerImpl` class (which is a subclass of `X509ExtendedTrustManager` and is what is passed back in the original `getTrustManagers`) it tries to call a function with type signature `X509Certificate[], String, String` which I can't find anywhere.

I'd look further into this, but I don't have the time at the moment.

**Comment by jakev** [comment]
@theSmallNothing the AOSP package `platform_external_conscrypt` looks relatively new - I've personally never looked into it.  Maybe [this](https://android.googlesource.com/platform/external/conscrypt/+/android-5.1.1_r2/src/platform/java/org/conscrypt/TrustManagerImpl.java#217) is the method you're talking about?

**Comment by theSmallNothing** [comment]
@jakev Yes, that's it, thanks. Yeah a lot of system components seem to be using it now, hooked it and apps stopped crashing. I'll write a patch if I have a spare moment.

**Comment by Fuzion24** [comment]
See #7
