### ISSUE TITLE
access_denied (49) - When access control was applied the certificate was rejected

### ISSUE THREAD

**Issue by StupidRepo** [Fuzion24/JustTrustMe#68]
I've selected the app under the module in LSPosed, yet Charles is still telling me `access_denied (49) - When access control was applied the certificate was rejected`. I have the Charles certificates added. Why's it not working?

**Comment by jpstotz** [comment]
There are many possible causes:

1. The app performs certificate pinning in a way that is not detected by JustTrustMe (can happen when the app is heavily obfuscated or if custom code is used for pinning).
2. LSPosed only affects Java/Kotlin (thus DEX code) code. If the app does not make use of DEX based code for TLS connections and pinning, JustTrustMe will not have an effect on those connections.
