### ISSUE TITLE
YikYak not working

### ISSUE THREAD

**Issue by teknogeek** [Fuzion24/JustTrustMe#8]
I am proxying YikYak to Charles with ProxyDroid and it is not sending some requests through. They get stuck with a `CONNECT IP:443 HTTP/1.0` and never go through due to pinning

**Comment by ctrlaltdylan** [comment]
Did you ever find a way around this?

**Comment by teknogeek** [comment]
Yes I did

**Comment by ctrlaltdylan** [comment]
Can you elaborate? I'm doing something similar with Burp + xposed + ssl kill but certain endpoints still are pinned. Did you need to use a special fork of this or another type of config?

**Comment by teknogeek** [comment]
I ended up writing my own code for it. I cannot elaborate much since I am
bound to contract...

**Comment by ctrlaltdylan** [comment]
Ah ok. Sounds like you and I are in similar situations.

**Comment by Fuzion24** [comment]
Feel free to contribute the code back.
